

RMSE results 

```{r}
getRDS = function(s){paste0("../_data/_sim-runs/_run",s,"/results.RDS")}
setups = as.list(1:14)
runs = as.list(1:108)
extractRMSEs = function(x){x$RMSEs}
retriveRMSES = function(s){
  path = getRDS(s)
  result = readRDS(path)
  res = mapply(extractRMSEs, result)
  return(t(res))
}
RMSEs = lapply(setups, retriveRMSES)
array_RMSEs = abind::abind(RMSEs, along = 3)
path = getRDS(1)
result = readRDS(path)
res = mapply(extractRMSEs, result)
met_names = rownames(res)
dat = data.frame("methods" = rep(rep(met_names, each = 108), 14),
              "setups" = rep(1:14, each = 108*8),
              "RMSE" = as.vector(array_RMSEs),
              "run" = rep(rep(1:108,  8),  14))
dat$methods = factor(dat$methods, levels = met_names)

write.csv(dat, "../_data/_sim-results/RMSEs.csv")
```


Correlations

```{r}
extractCors = function(x){x$cors}
retriveCors = function(s){
  path = getRDS(s)
  result = readRDS(path)
  res = mapply(extractCors, result)
  return(t(res))
}
Cors = lapply(setups, retriveCors)
array_Cors = abind::abind(Cors, along = 3)
met_names_2 = c("True", met_names)
dat = data.frame("methods" = rep(rep(met_names_2, each = 108*15), 14),
              "setups" = rep(1:14, each = 108*9*15),
              "Cors" = as.vector(array_Cors),
              "run" = rep(rep(1:108,  9*15),  14),
              "element" = rep(rep(rep(1:15, each =108), 9),14))

dat$methods = factor(dat$methods, levels = met_names_2)

write.csv(dat, "../_data/_sim-results/CORRs.csv")
```



```{r}
extractPostSig2Fplus = function(x){
  Del = x$factor_models_output$del2.2Fplus
  Lamb = x$factor_models_output$lambda.2Fplus
  d = dim(Del)
  inds = upper.tri(matrix(NA, d[2], d[2]))
  num_cors = sum(inds)
  cor_val = matrix(NA, d[1], num_cors)
  for (m in 1:d[1]){
    cor_mat = cov2cor(crossprod(t(Lamb[m,,]))+diag(Del[m,]))
    cor_val[m,] = cor_mat[inds]
  }
  return(cor_val)
}

retrivePostSig2Fplus = function(s){
  path = getRDS(s)
  result = readRDS(path)
  Cors.2Fplus = lapply(result, extractPostSig2Fplus)
  Cors.2Fplus_array = abind::abind(Cors.2Fplus, along = 3)
  return(Cors.2Fplus_array)
}

Cors.2Fplus = lapply(setups, retrivePostSig2Fplus)
Cors.2Fplus_array = abind::abind(Cors.2Fplus, along = 4)
dat.2Fplus = data.frame("methods" = "2F+",
              "setups" = rep(1:14, each = 108*15*4000),
              "Cors" = as.vector(Cors.2Fplus_array),
              "run" = rep(rep(1:108, each = 4000*15),14),
              "iter" = rep(rep(rep(1:4000, 15), 108), 14),
              "element" = rep(rep(rep(1:15, each = 4000), 108), 14))
```



```{r}
lower_CI = tapply(dat.2Fplus$Cors, 
                  list(dat.2Fplus$run, 
                       dat.2Fplus$element, 
                       dat.2Fplus$setups), 
                  function(x) quantile(x, probs = .025))
upper_CI = tapply(dat.2Fplus$Cors, 
                  list(dat.2Fplus$run, 
                       dat.2Fplus$element, 
                       dat.2Fplus$setups), 
                  function(x) quantile(x, probs = .975))
t.cor = readRDS("../_data/_ground-truths/correlations.RDS")
extractTCors = function(x){
  ind = upper.tri(x)
  x[ind]
}
t.cor_array = mapply(extractTCors, t.cor)
t.cor_array = array(rep(as.vector(t.cor_array), each = 108), dim = c(108, 15, 14))

result = t.cor_array >= lower_CI & t.cor_array <= upper_CI
apply(result, 2:3, function(x) sum(x)/length(x))
```




```{r}
extractPostSig2F = function(x){
  Del = x$factor_models_output$del2.2F
  Lamb = x$factor_models_output$lambda.2
  d = dim(Del)
  inds = upper.tri(matrix(NA, d[2], d[2]))
  num_cors = sum(inds)
  cor_val = matrix(NA, d[1], num_cors)
  for (m in 1:d[1]){
    cor_mat = cov2cor(crossprod(t(Lamb[m,,]))+diag(Del[m,]))
    cor_val[m,] = cor_mat[inds]
  }
  return(cor_val)
}

retrivePostSig2F = function(s){
  path = getRDS(s)
  result = readRDS(path)
  Cors.2F = lapply(result, extractPostSig2F)
  Cors.2F_array = abind::abind(Cors.2F, along = 3)
  return(Cors.2F_array)
}

Cors.2F = lapply(setups, retrivePostSig2F)
Cors.2F_array = abind::abind(Cors.2F, along = 4)
dat.2F = data.frame("methods" = "2F",
              "setups" = rep(1:14, each = 108*15*4000),
              "Cors" = as.vector(Cors.2F_array),
              "run" = rep(rep(1:108, each = 4000*15),14),
              "iter" = rep(rep(rep(1:4000, 15), 108), 14),
              "element" = rep(rep(rep(1:15, each = 4000), 108), 14))
```




```{r}
lower_CI = tapply(dat.2F$Cors, 
                  list(dat.2F$run, 
                       dat.2F$element, 
                       dat.2F$setups), 
                  function(x) quantile(x, probs = .025))
upper_CI = tapply(dat.2F$Cors, 
                  list(dat.2F$run, 
                       dat.2F$element, 
                       dat.2F$setups), 
                  function(x) quantile(x, probs = .975))
t.cor = readRDS("../_data/_ground-truths/correlations.RDS")
extractTCors = function(x){
  ind = upper.tri(x)
  x[ind]
}
t.cor_array = mapply(extractTCors, t.cor)
t.cor_array = array(rep(as.vector(t.cor_array), each = 108), dim = c(108, 15, 14))

result = t.cor_array >= lower_CI & t.cor_array <= upper_CI
apply(result, 2:3, function(x) sum(x)/length(x))
```

```{r}
extractPostSigIW = function(x){
  Sig = x$factor_models_output$pSig2.wishart
  d = dim(Sig)
  inds = upper.tri(matrix(NA, d[2], d[2]))
  num_cors = sum(inds)
  cor_val = matrix(NA, d[1], num_cors)
  for (m in 1:d[1]){
    cor_mat = cov2cor(solve(Sig[m,,]))
    cor_val[m,] = cor_mat[inds]
  }
  return(cor_val)
}

retrivePostSigIW = function(s){
  path = getRDS(s)
  result = readRDS(path)
  Cors.IW = lapply(result, extractPostSigIW)
  Cors.IW_array = abind::abind(Cors.IW, along = 3)
  return(Cors.IW_array)
}

Cors.IW = lapply(setups, retrivePostSigIW)
Cors.IW_array = abind::abind(Cors.IW, along = 4)
dat.IW = data.frame("methods" = "IW",
              "setups" = rep(1:14, each = 108*15*4000),
              "Cors" = as.vector(Cors.IW_array),
              "run" = rep(rep(1:108, each = 4000*15),14),
              "iter" = rep(rep(rep(1:4000, 15), 108), 14),
              "element" = rep(rep(rep(1:15, each = 4000), 108), 14))
```

```{r}
lower_CI = tapply(dat.IW$Cors, 
                  list(dat.IW$run, 
                       dat.IW$element, 
                       dat.IW$setups), 
                  function(x) quantile(x, probs = .025))
upper_CI = tapply(dat.IW$Cors, 
                  list(dat.IW$run, 
                       dat.IW$element, 
                       dat.IW$setups), 
                  function(x) quantile(x, probs = .975))
t.cor = readRDS("../_data/_ground-truths/correlations.RDS")
extractTCors = function(x){
  ind = upper.tri(x)
  x[ind]
}
t.cor_array = mapply(extractTCors, t.cor)
t.cor_array = array(rep(as.vector(t.cor_array), each = 108), dim = c(108, 15, 14))

result = t.cor_array >= lower_CI & t.cor_array <= upper_CI
apply(result, 2:3, function(x) sum(x)/length(x))
```